import { createSlice } from "@reduxjs/toolkit";

export const initialState={

}
export const authSlice = createSlice({
    name: 'auth',
    initialState,
    
    reducers: {
      
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
      builder
        // .addCase(incrementAsync.pending, (state) => {
        //   state.status = 'loading';
        // })
        // .addCase(incrementAsync.fulfilled, (state, action) => {
        //   state.status = 'idle';
        //   state.value += action.payload;
        // })
        // .addCase(incrementAsync.rejected, (state) => {
        //   state.status = 'failed';
        // });
    },
  });